/**
 * Route Map - Maps ActivePage IDs to their React component renders.
 * Extracted from Index.tsx to reduce file size.
 */
import React from 'react';
import type { ActivePage } from '@/types';

// Lazy imports for code splitting
import { Dashboard } from '@/components/Dashboard';
import { SetupGuard } from '@/components/setup/SetupGuard';
import { CustomerForm } from '@/components/forms/CustomerForm';
import { SupplierForm } from '@/components/forms/SupplierForm';
import { PurchaseInvoiceForm } from '@/components/forms/PurchaseInvoiceForm';
import { SalesInvoiceForm } from '@/components/forms/SalesInvoiceForm';
import { CustomersTable } from '@/components/tables/CustomersTable';
import { SuppliersTable } from '@/components/tables/SuppliersTable';
import { PurchasesTable } from '@/components/tables/PurchasesTable';
import { SalesTable } from '@/components/tables/SalesTable';
import { PartnerDealershipsTable } from '@/components/tables/PartnerDealershipsTable';
import { CarTransfersTable } from '@/components/tables/CarTransfersTable';
import { InventoryReport } from '@/components/reports/InventoryReport';
import { ProfitReport } from '@/components/reports/ProfitReport';
import { PurchasesReport } from '@/components/reports/PurchasesReport';
import { SalesReport } from '@/components/reports/SalesReport';
import { CustomersReport } from '@/components/reports/CustomersReport';
import { SuppliersReport } from '@/components/reports/SuppliersReport';
import { CommissionsReport } from '@/components/reports/CommissionsReport';
import { TransfersReport } from '@/components/reports/TransfersReport';
import { PartnerDealershipReport } from '@/components/reports/PartnerDealershipReport';
import { ExpensesReport } from '@/components/reports/ExpensesReport';
import { PrepaidExpensesReport } from '@/components/reports/PrepaidExpensesReport';
import { UsersManagement } from '@/components/UsersManagement';
import { AppSettingsPage } from '@/components/AppSettings';
import { TaxSettingsPage } from '@/components/accounting/TaxSettingsPage';
import { ChartOfAccountsPage } from '@/components/accounting/ChartOfAccountsPage';
import { JournalEntriesPage } from '@/components/accounting/JournalEntriesPage';
import { CostCentersPage } from '@/components/accounting/CostCentersPage';
import { FinancialReportsPage } from '@/components/accounting/FinancialReportsPage';
import { GeneralLedgerPage } from '@/components/accounting/GeneralLedgerPage';
import { ZakatReportsPage } from '@/components/accounting/ZakatReportsPage';
import { FiscalYearsPage } from '@/components/accounting/FiscalYearsPage';
import { ExpensesPage } from '@/components/expenses/ExpensesPage';
import PrepaidExpensesPage from '@/components/expenses/PrepaidExpensesPage';
import { QuotationsPage } from '@/components/quotations/QuotationsPage';
import { InstallmentsPage } from '@/components/installments/InstallmentsPage';
import { VouchersPage } from '@/components/vouchers/VouchersPage';
import { AuditLogsPage } from '@/components/audit/AuditLogsPage';
import { BackupsPage } from '@/components/backups/BackupsPage';
import { FinancingPage } from '@/components/financing/FinancingPage';
import { BankingPage } from '@/components/banking/BankingPage';
import { TrialBalancePage } from '@/components/accounting/TrialBalancePage';
import { ComprehensiveFinancialStatementsPage } from '@/components/financial-statements';
import { VATReturnReportPage } from '@/components/accounting/VATReturnReportPage';
import { EmployeesPage } from '@/components/payroll/EmployeesPage';
import { PayrollPage } from '@/components/payroll/PayrollPage';
import { AccountStatementReport } from '@/components/reports/AccountStatementReport';
import { AccountMovementReport } from '@/components/reports/AccountMovementReport';
import { ControlCenterPage } from '@/components/control-center/ControlCenterPage';
import { AccountingAuditPage } from '@/components/audit/AccountingAuditPage';
import { FixedAssetsPage } from '@/components/assets/FixedAssetsPage';
import { MedadImportPage } from '@/components/import/MedadImportPage';
import { ProjectsPage, ContractsPage, ProgressBillingsPage } from '@/components/construction';
import { CustodyPage } from '@/components/custody';
import { TripsPage } from '@/components/trips';
import { ThemeSettingsPage } from '@/components/themes/ThemeSettingsPage';
import { MenuManagementPage, OrdersPage, KitchenPage, TablesPage } from '@/components/restaurant';
import { ShipmentsPage, LettersOfCreditPage, CustomsClearancePage } from '@/components/export-import';
import { TasksPage } from '@/components/tasks/TasksPage';
import { WarehousesPage, ItemsPage, UnitsPage, CategoriesPage } from '@/components/inventory';
import { AgingReportPage } from '@/components/receivables/AgingReportPage';
import { ChecksPage } from '@/components/checks/ChecksPage';
import { BudgetsPage } from '@/components/budgets/BudgetsPage';
import { FinancialKPIsPage } from '@/components/reports/FinancialKPIsPage';
import { ApprovalsPage } from '@/components/approvals/ApprovalsPage';
import { AttendanceManagementHub } from '@/components/hr/attendance/AttendanceManagementHub';
import { FingerprintDevicesPage } from '@/components/hr/FingerprintDevicesPage';
import { LeavesPage } from '@/components/hr/LeavesPage';
import { ManufacturingPage } from '@/components/manufacturing/ManufacturingPage';
import { IntegrationsPage } from '@/components/integrations/IntegrationsPage';
import { CurrenciesPage } from '@/components/currencies/CurrenciesPage';
import { BranchesPage } from '@/components/branches/BranchesPage';
import { ApiManagementPage } from '@/components/api/ApiManagementPage';
import { PluginsPage } from '@/components/plugins/PluginsPage';
import {
  ZatcaPluginPage, AdvancedHRPluginPage, MultiWarehousePluginPage,
  BIAnalyticsPluginPage, POSPluginPage, WhatsAppPluginPage,
  IFRSPluginPage, ProjectMgmtPluginPage
} from '@/components/plugins/pages';
import { CashFlowForecastPage } from '@/components/cashflow/CashFlowForecastPage';
import { ExecutiveKPIDashboard } from '@/components/kpi/ExecutiveKPIDashboard';
import { CommissionsSystemPage } from '@/components/commissions/CommissionsSystemPage';
import { BranchComparisonPage } from '@/components/branches/BranchComparisonPage';
import { AISalesForecastPage } from '@/components/sales-forecast/AISalesForecastPage';
import { PurchaseOrdersPage, GoodsReceiptPage, PurchaseReturnsPage, MaterialsRequestPage, ContractorPaymentPage } from '@/components/procurement';
import { StockVouchersPage } from '@/components/inventory/StockVouchersPage';
import { StocktakingPage } from '@/components/inventory/StocktakingPage';
import { SalesReturnsPage } from '@/components/returns/SalesReturnsPage';
import { CRMPage } from '@/components/crm/CRMPage';
import { LoyaltyPage } from '@/components/loyalty/LoyaltyPage';
import { SubscriptionsPage } from '@/components/subscriptions/SubscriptionsPage';
import { WorkOrdersPage } from '@/components/work-orders/WorkOrdersPage';
import { BookingsPage } from '@/components/bookings/BookingsPage';
import { TimeTrackingPage } from '@/components/time-tracking/TimeTrackingPage';
import { EmployeeContractsPage } from '@/components/hr/ContractsPage';
import { OrgStructurePage } from '@/components/hr/OrgStructurePage';
import { RentalsPage } from '@/components/rentals/RentalsPage';
import { SalesTargetsPage } from '@/components/sales-targets/SalesTargetsPage';
import { PaymentGatewayPage } from '@/components/payment-gateway/PaymentGatewayPage';
import { BookkeepingServicePage } from '@/components/bookkeeping/BookkeepingServicePage';
import { ZatcaSandboxPage } from '@/components/zatca-sandbox/ZatcaSandboxPage';
import { ZatcaTechnicalDocPage } from '@/components/zatca-sandbox/ZatcaTechnicalDocPage';
import { CustomerPortalPage } from '@/components/customer-portal/CustomerPortalPage';
import { SupplierPortalPage } from '@/components/supplier-portal/SupplierPortalPage';
import { ApprovalDashboard } from '@/components/approvals/ApprovalDashboard';
import { WhatsAppIntegration } from '@/components/integrations/WhatsAppIntegration';
import { AdvancedAnalyticsDashboard } from '@/components/reports/AdvancedAnalyticsDashboard';
import { AdvancedProjectsPage } from '@/components/advanced-projects/AdvancedProjectsPage';
import { REProjectsPage, REUnitsPage, REContractorsPage, RECRMPage, REReportsPage, REAfterSalesPage, REClientPortalPage } from '@/components/real-estate';
import { MobileInventoryPage } from '@/components/mobile-inventory/MobileInventoryPage';
import { MobileInvoiceReaderPage } from '@/components/mobile-invoice/MobileInvoiceReaderPage';
import { DeveloperApiPage } from '@/components/developer-api/DeveloperApiPage';
import { EcommercePage } from '@/components/ecommerce/EcommercePage';
import { SmsMarketingPage } from '@/components/marketing/SmsMarketingPage';
import { SocialMarketingPage } from '@/components/marketing/SocialMarketingPage';
import { EventsPage } from '@/components/events/EventsPage';
import { SurveysPage } from '@/components/surveys/SurveysPage';
import { ElearningPage } from '@/components/elearning/ElearningPage';
import { KnowledgeBasePage } from '@/components/knowledge/KnowledgeBasePage';
import { InternalChatPage } from '@/components/internal-chat/InternalChatPage';
import { ESignaturePage } from '@/components/e-signature/ESignaturePage';
import { PlanningPage } from '@/components/planning/PlanningPage';
import { AppointmentsPage } from '@/components/appointments/AppointmentsPage';
import { FieldServicePage } from '@/components/field-service/FieldServicePage';
import { PLMPage } from '@/components/plm/PLMPage';
import { BarcodeScannerPage } from '@/components/barcode/BarcodeScannerPage';
import { SupportContact } from '@/components/SupportContact';
import { FieldLevelSecurityPage } from '@/components/security/FieldLevelSecurityPage';
import { InvoiceApprovalWorkflow } from '@/components/approvals/InvoiceApprovalWorkflow';
import { EcommerceIntegrationPage } from '@/components/integrations/EcommerceIntegrationPage';
import { PublicApiDocsPage } from '@/components/api-docs/PublicApiDocsPage';
import { DataImportPage } from '@/components/import/DataImportPage';
import { AutomationPage } from '@/components/automation/AutomationPage';
import { ExpenseOCRPage } from '@/components/expenses/ExpenseOCRPage';
import { OverdueInvoicesPage } from '@/components/notifications/OverdueInvoicesPage';
import { HelpdeskPage } from '@/components/helpdesk/HelpdeskPage';
import { CMSPage } from '@/components/cms/CMSPage';
import { POSPage } from '@/components/pos/POSPage';
import { WorkflowsPage } from '@/components/workflows';
import { CreditDebitNotesPage } from '@/components/returns/CreditDebitNotesPage';

interface RenderContentProps {
  activePage: ActivePage;
  setActivePage: (page: ActivePage) => void;
  stats: any;
  isStatsLoading: boolean;
  isFocusMode: boolean;
  onToggleFocusMode: () => void;
}

export function renderPageContent({
  activePage, setActivePage, stats, isStatsLoading, isFocusMode, onToggleFocusMode
}: RenderContentProps): React.ReactNode {
  switch (activePage) {
    case 'dashboard': return <SetupGuard setActivePage={setActivePage}><Dashboard stats={stats} setActivePage={setActivePage} isLoading={isStatsLoading} isFocusMode={isFocusMode} onToggleFocusMode={onToggleFocusMode} /></SetupGuard>;
    case 'customers': return <CustomersTable setActivePage={setActivePage} />;
    case 'suppliers': return <SuppliersTable setActivePage={setActivePage} />;
    case 'purchases': return <PurchasesTable setActivePage={setActivePage} />;
    case 'sales': return <SalesTable setActivePage={setActivePage} />;
    case 'add-customer': return <CustomerForm setActivePage={setActivePage} />;
    case 'add-supplier': return <SupplierForm setActivePage={setActivePage} />;
    case 'add-purchase': case 'add-purchase-invoice': return <PurchaseInvoiceForm setActivePage={setActivePage} />;
    case 'add-sale': case 'add-sale-invoice': return <SalesInvoiceForm setActivePage={setActivePage} />;
    case 'partner-dealerships': return <PartnerDealershipsTable setActivePage={setActivePage} />;
    case 'car-transfers': return <CarTransfersTable setActivePage={setActivePage} />;
    case 'inventory-report': return <InventoryReport />;
    case 'profit-report': return <ProfitReport />;
    case 'purchases-report': return <PurchasesReport />;
    case 'sales-report': return <SalesReport />;
    case 'customers-report': return <CustomersReport />;
    case 'suppliers-report': return <SuppliersReport />;
    case 'commissions-report': return <CommissionsReport />;
    case 'transfers-report': return <TransfersReport />;
    case 'partner-report': return <PartnerDealershipReport setActivePage={setActivePage} />;
    case 'users-management': return <UsersManagement setActivePage={setActivePage} />;
    case 'app-settings': return <AppSettingsPage setActivePage={setActivePage} />;
    case 'tax-settings': return <TaxSettingsPage />;
    case 'chart-of-accounts': return <ChartOfAccountsPage />;
    case 'journal-entries': return <JournalEntriesPage />;
    case 'financial-reports': return <FinancialReportsPage />;
    case 'general-ledger': return <GeneralLedgerPage />;
    case 'expenses': return <ExpensesPage />;
    case 'prepaid-expenses': return <PrepaidExpensesPage />;
    case 'expenses-report': return <ExpensesReport />;
    case 'prepaid-expenses-report': return <PrepaidExpensesReport />;
    case 'quotations': return <QuotationsPage />;
    case 'installments': return <InstallmentsPage />;
    case 'vouchers': return <VouchersPage />;
    case 'audit-logs': return <AuditLogsPage />;
    case 'backups': return <BackupsPage />;
    case 'financing': return <FinancingPage />;
    case 'banking': return <BankingPage />;
    case 'zakat-reports': return <ZakatReportsPage />;
    case 'fiscal-years': return <FiscalYearsPage />;
    case 'trial-balance': return <TrialBalancePage />;
    case 'financial-statements': return <ComprehensiveFinancialStatementsPage />;
    case 'vat-return-report': return <VATReturnReportPage />;
    case 'employees': return <EmployeesPage />;
    case 'payroll': return <PayrollPage />;
    case 'account-statement': return <AccountStatementReport />;
    case 'control-center': return <ControlCenterPage />;
    case 'fixed-assets': return <FixedAssetsPage />;
    case 'medad-import': return <MedadImportPage />;
    case 'projects': return <ProjectsPage />;
    case 'contracts': return <ContractsPage />;
    case 'progress-billings': return <ProgressBillingsPage />;
    case 'custody': return <CustodyPage />;
    case 'trips': return <TripsPage />;
    case 'account-movement': return <AccountMovementReport />;
    case 'theme-settings': return <ThemeSettingsPage />;
    case 'menu-management': return <MenuManagementPage />;
    case 'restaurant-orders': return <OrdersPage />;
    case 'kitchen-display': return <KitchenPage />;
    case 'table-management': return <TablesPage />;
    case 'shipments': return <ShipmentsPage />;
    case 'letters-of-credit': return <LettersOfCreditPage />;
    case 'customs-clearance': return <CustomsClearancePage />;
    case 'accounting-audit': return <AccountingAuditPage />;
    case 'cost-centers': return <CostCentersPage />;
    case 'tasks': return <TasksPage />;
    case 'warehouses': return <WarehousesPage />;
    case 'items-catalog': return <ItemsPage />;
    case 'item-categories': return <CategoriesPage />;
    case 'units-of-measure': return <UnitsPage />;
    case 'aging-report': return <AgingReportPage />;
    case 'checks': return <ChecksPage />;
    case 'budgets': return <BudgetsPage />;
    case 'financial-kpis': return <FinancialKPIsPage />;
    case 'approvals': return <ApprovalDashboard />;
    case 'attendance': return <AttendanceManagementHub />;
    case 'fingerprint-devices': return <FingerprintDevicesPage />;
    case 'leaves': return <LeavesPage />;
    case 'manufacturing': return <ManufacturingPage />;
    case 'integrations': return <IntegrationsPage />;
    case 'currencies': return <CurrenciesPage />;
    case 'branches': return <BranchesPage />;
    case 'api-management': return <ApiManagementPage />;
    case 'plugins': return <PluginsPage setActivePage={setActivePage as any} />;
    case 'plugin-zatca': return <ZatcaPluginPage />;
    case 'plugin-advanced-hr': return <AdvancedHRPluginPage />;
    case 'plugin-multi-warehouse': return <MultiWarehousePluginPage />;
    case 'plugin-bi-analytics': return <BIAnalyticsPluginPage />;
    case 'cashflow-forecast': return <CashFlowForecastPage />;
    case 'executive-kpis': return <ExecutiveKPIDashboard />;
    case 'commissions-system': return <CommissionsSystemPage />;
    case 'branch-comparison': return <BranchComparisonPage />;
    case 'ai-sales-forecast': return <AISalesForecastPage />;
    case 'plugin-pos': return <POSPluginPage />;
    case 'plugin-whatsapp': return <WhatsAppPluginPage />;
    case 'plugin-ifrs': return <IFRSPluginPage />;
    case 'plugin-project-mgmt': return <ProjectMgmtPluginPage />;
    case 'workflows': return <WorkflowsPage />;
    case 'automation': return <AutomationPage />;
    case 'purchase-orders': return <PurchaseOrdersPage />;
    case 'goods-receipt': return <GoodsReceiptPage />;
    case 'purchase-returns': return <PurchaseReturnsPage />;
    case 'materials-request': return <MaterialsRequestPage />;
    case 'contractor-payment': return <ContractorPaymentPage />;
    case 'stock-vouchers': return <StockVouchersPage />;
    case 'stocktaking': return <StocktakingPage />;
    case 'credit-debit-notes': return <SalesReturnsPage />;
    case 'crm': return <CRMPage />;
    case 'loyalty': return <LoyaltyPage />;
    case 'subscriptions': return <SubscriptionsPage />;
    case 'work-orders': return <WorkOrdersPage />;
    case 'bookings': return <BookingsPage />;
    case 'time-tracking': return <TimeTrackingPage />;
    case 'employee-contracts': return <EmployeeContractsPage />;
    case 'org-structure': return <OrgStructurePage />;
    case 'rentals': return <RentalsPage />;
    case 'sales-targets': return <SalesTargetsPage />;
    case 'payment-gateway': return <PaymentGatewayPage />;
    case 'bookkeeping-service': return <BookkeepingServicePage />;
    case 'zatca-sandbox': return <ZatcaSandboxPage />;
    case 'zatca-technical-doc': return <ZatcaTechnicalDocPage />;
    case 'customer-portal': return <CustomerPortalPage />;
    case 'supplier-portal': return <SupplierPortalPage />;
    case 'whatsapp-integration': return <WhatsAppIntegration />;
    case 'advanced-analytics': return <AdvancedAnalyticsDashboard />;
    case 'advanced-projects': return <AdvancedProjectsPage />;
    case 're-projects': return <REProjectsPage />;
    case 're-units': return <REUnitsPage />;
    case 're-contractors': return <REContractorsPage />;
    case 're-crm': return <RECRMPage />;
    case 're-reports': return <REReportsPage />;
    case 're-after-sales': return <REAfterSalesPage />;
    case 're-client-portal': return <REClientPortalPage />;
    case 'mobile-inventory': return <MobileInventoryPage />;
    case 'mobile-invoice-reader': return <MobileInvoiceReaderPage />;
    case 'developer-api': return <DeveloperApiPage />;
    case 'ecommerce': return <EcommercePage />;
    case 'helpdesk': return <HelpdeskPage />;
    case 'cms': return <CMSPage />;
    case 'pos': return <POSPage />;
    case 'sms-marketing': return <SmsMarketingPage />;
    case 'social-marketing': return <SocialMarketingPage />;
    case 'events': return <EventsPage />;
    case 'surveys': return <SurveysPage />;
    case 'elearning': return <ElearningPage />;
    case 'knowledge-base': return <KnowledgeBasePage />;
    case 'internal-chat': return <InternalChatPage />;
    case 'e-signature': return <ESignaturePage />;
    case 'planning': return <PlanningPage />;
    case 'appointments': return <AppointmentsPage />;
    case 'field-service': return <FieldServicePage />;
    case 'plm': return <PLMPage />;
    case 'barcode-scanner': return <BarcodeScannerPage />;
    case 'support-contact': return <SupportContact />;
    case 'field-level-security': return <FieldLevelSecurityPage />;
    case 'invoice-approval-workflow': return <InvoiceApprovalWorkflow />;
    case 'ecommerce-integration': return <EcommerceIntegrationPage />;
    case 'public-api-docs': return <PublicApiDocsPage />;
    case 'data-import': return <DataImportPage />;
    case 'expense-ocr': return <ExpenseOCRPage />;
    case 'overdue-invoices': return <OverdueInvoicesPage />;
    default:
      return <SetupGuard setActivePage={setActivePage}><Dashboard stats={stats} setActivePage={setActivePage} isLoading={isStatsLoading} isFocusMode={isFocusMode} onToggleFocusMode={onToggleFocusMode} /></SetupGuard>;
  }
}
