
-- =====================================================
-- STEP 1: Delete all existing COA templates to rebuild fresh
-- =====================================================
DELETE FROM coa_templates;

-- =====================================================
-- CAR DEALERSHIP - شجرة حسابات معارض السيارات
-- =====================================================
INSERT INTO coa_templates (code, name, name_en, type, parent_code, is_header, sort_order, company_type) VALUES
-- الأصول
('1', 'الأصول', 'Assets', 'asset', NULL, true, 1, 'car_dealership'),
('11', 'الأصول المتداولة', 'Current Assets', 'asset', '1', true, 2, 'car_dealership'),
('1101', 'الصندوق', 'Cash', 'asset', '11', false, 3, 'car_dealership'),
('1102', 'البنك', 'Bank', 'asset', '11', false, 4, 'car_dealership'),
('1103', 'نقاط البيع', 'POS', 'asset', '11', false, 5, 'car_dealership'),
('1104', 'شيكات تحت التحصيل', 'Checks Under Collection', 'asset', '11', false, 6, 'car_dealership'),
('12', 'الذمم المدينة', 'Receivables', 'asset', '1', true, 7, 'car_dealership'),
('1201', 'العملاء', 'Customers', 'asset', '12', false, 8, 'car_dealership'),
('1202', 'أوراق قبض', 'Notes Receivable', 'asset', '12', false, 9, 'car_dealership'),
('1203', 'عربون سيارات', 'Vehicle Deposits', 'asset', '12', false, 10, 'car_dealership'),
('1204', 'ذمم مدينة أخرى', 'Other Receivables', 'asset', '12', false, 11, 'car_dealership'),
('13', 'المخزون', 'Inventory', 'asset', '1', true, 12, 'car_dealership'),
('1301', 'مخزون السيارات الجديدة', 'New Vehicle Inventory', 'asset', '13', false, 13, 'car_dealership'),
('1302', 'مخزون السيارات المستعملة', 'Used Vehicle Inventory', 'asset', '13', false, 14, 'car_dealership'),
('1303', 'قطع الغيار', 'Spare Parts', 'asset', '13', false, 15, 'car_dealership'),
('1304', 'زيوت ومواد استهلاكية', 'Oils & Consumables', 'asset', '13', false, 16, 'car_dealership'),
('14', 'الأصول الثابتة', 'Fixed Assets', 'asset', '1', true, 17, 'car_dealership'),
('1401', 'مباني المعرض', 'Showroom Buildings', 'asset', '14', false, 18, 'car_dealership'),
('1402', 'أثاث وتجهيزات', 'Furniture & Fixtures', 'asset', '14', false, 19, 'car_dealership'),
('1403', 'أجهزة حاسب', 'Computer Equipment', 'asset', '14', false, 20, 'car_dealership'),
('1404', 'سيارات نقل وخدمة', 'Service Vehicles', 'asset', '14', false, 21, 'car_dealership'),
('1405', 'معدات الورشة', 'Workshop Equipment', 'asset', '14', false, 22, 'car_dealership'),
('1406', 'مجمع الإهلاك', 'Accumulated Depreciation', 'asset', '14', false, 23, 'car_dealership'),
('15', 'مصروفات مدفوعة مقدماً', 'Prepaid Expenses', 'asset', '1', true, 24, 'car_dealership'),
('1501', 'إيجار مدفوع مقدماً', 'Prepaid Rent', 'asset', '15', false, 25, 'car_dealership'),
('1502', 'تأمين مدفوع مقدماً', 'Prepaid Insurance', 'asset', '15', false, 26, 'car_dealership'),
-- الالتزامات
('2', 'الالتزامات', 'Liabilities', 'liability', NULL, true, 30, 'car_dealership'),
('21', 'الالتزامات المتداولة', 'Current Liabilities', 'liability', '2', true, 31, 'car_dealership'),
('2101', 'الموردون', 'Suppliers', 'liability', '21', false, 32, 'car_dealership'),
('2102', 'ضريبة القيمة المضافة', 'VAT Payable', 'liability', '21', false, 33, 'car_dealership'),
('2103', 'أوراق دفع', 'Notes Payable', 'liability', '21', false, 34, 'car_dealership'),
('2104', 'رواتب مستحقة', 'Accrued Salaries', 'liability', '21', false, 35, 'car_dealership'),
('2105', 'مصروفات مستحقة', 'Accrued Expenses', 'liability', '21', false, 36, 'car_dealership'),
('2106', 'عربون عملاء', 'Customer Deposits', 'liability', '21', false, 37, 'car_dealership'),
('2107', 'تأمينات اجتماعية مستحقة', 'Social Insurance Payable', 'liability', '21', false, 38, 'car_dealership'),
('22', 'الالتزامات طويلة الأجل', 'Long-term Liabilities', 'liability', '2', true, 39, 'car_dealership'),
('2201', 'قروض تمويل المخزون', 'Inventory Financing Loans', 'liability', '22', false, 40, 'car_dealership'),
('2202', 'قروض بنكية طويلة الأجل', 'Long-term Bank Loans', 'liability', '22', false, 41, 'car_dealership'),
-- حقوق الملكية
('3', 'حقوق الملكية', 'Equity', 'equity', NULL, true, 50, 'car_dealership'),
('31', 'رأس المال', 'Capital', 'equity', '3', true, 51, 'car_dealership'),
('3101', 'رأس المال المدفوع', 'Paid-in Capital', 'equity', '31', false, 52, 'car_dealership'),
('3102', 'جاري الشريك', 'Partner Current Account', 'equity', '31', false, 53, 'car_dealership'),
('32', 'الاحتياطيات والأرباح', 'Reserves & Earnings', 'equity', '3', true, 54, 'car_dealership'),
('3201', 'الأرباح المحتجزة', 'Retained Earnings', 'equity', '32', false, 55, 'car_dealership'),
('3202', 'الاحتياطي النظامي', 'Legal Reserve', 'equity', '32', false, 56, 'car_dealership'),
('3203', 'أرباح العام', 'Current Year Profit', 'equity', '32', false, 57, 'car_dealership'),
-- الإيرادات
('4', 'الإيرادات', 'Revenue', 'revenue', NULL, true, 60, 'car_dealership'),
('41', 'إيرادات المبيعات', 'Sales Revenue', 'revenue', '4', true, 61, 'car_dealership'),
('4101', 'إيرادات مبيعات السيارات', 'Vehicle Sales Revenue', 'revenue', '41', false, 62, 'car_dealership'),
('4102', 'إيرادات قطع الغيار', 'Spare Parts Revenue', 'revenue', '41', false, 63, 'car_dealership'),
('4103', 'إيرادات الصيانة والخدمات', 'Service & Maintenance Revenue', 'revenue', '41', false, 64, 'car_dealership'),
('4104', 'عمولات الوساطة', 'Brokerage Commissions', 'revenue', '41', false, 65, 'car_dealership'),
('42', 'إيرادات أخرى', 'Other Revenue', 'revenue', '4', true, 66, 'car_dealership'),
('4201', 'إيرادات التمويل', 'Finance Income', 'revenue', '42', false, 67, 'car_dealership'),
('4202', 'خصم مكتسب', 'Purchase Discounts', 'revenue', '42', false, 68, 'car_dealership'),
('4203', 'إيرادات متنوعة', 'Miscellaneous Revenue', 'revenue', '42', false, 69, 'car_dealership'),
-- تكلفة المبيعات
('45', 'تكلفة المبيعات', 'Cost of Sales', 'expense', '4', true, 70, 'car_dealership'),
('4501', 'تكلفة السيارات المباعة', 'Cost of Vehicles Sold', 'expense', '45', false, 71, 'car_dealership'),
('4502', 'تكلفة قطع الغيار المباعة', 'Cost of Spare Parts Sold', 'expense', '45', false, 72, 'car_dealership'),
('4503', 'مصاريف الشحن والنقل', 'Shipping & Transport Costs', 'expense', '45', false, 73, 'car_dealership'),
-- المصروفات
('5', 'المصروفات', 'Expenses', 'expense', NULL, true, 80, 'car_dealership'),
('51', 'المصروفات التشغيلية', 'Operating Expenses', 'expense', '5', true, 81, 'car_dealership'),
('5101', 'رواتب وأجور', 'Salaries & Wages', 'expense', '51', false, 82, 'car_dealership'),
('5102', 'إيجار المعرض', 'Showroom Rent', 'expense', '51', false, 83, 'car_dealership'),
('5103', 'كهرباء ومياه', 'Electricity & Water', 'expense', '51', false, 84, 'car_dealership'),
('5104', 'صيانة ونظافة', 'Maintenance & Cleaning', 'expense', '51', false, 85, 'car_dealership'),
('5105', 'تأمين المعرض والسيارات', 'Showroom & Vehicle Insurance', 'expense', '51', false, 86, 'car_dealership'),
('5106', 'تسويق وإعلان', 'Marketing & Advertising', 'expense', '51', false, 87, 'car_dealership'),
('5107', 'مصاريف نقل سيارات', 'Vehicle Transport Expenses', 'expense', '51', false, 88, 'car_dealership'),
('5108', 'رسوم حكومية وتراخيص', 'Government Fees & Licenses', 'expense', '51', false, 89, 'car_dealership'),
('5109', 'أدوات مكتبية', 'Office Supplies', 'expense', '51', false, 90, 'car_dealership'),
('5110', 'اتصالات وإنترنت', 'Telecom & Internet', 'expense', '51', false, 91, 'car_dealership'),
('52', 'المصروفات الإدارية', 'Administrative Expenses', 'expense', '5', true, 92, 'car_dealership'),
('5201', 'مصاريف إدارية عامة', 'General Admin Expenses', 'expense', '52', false, 93, 'car_dealership'),
('5202', 'استشارات قانونية ومحاسبية', 'Legal & Accounting Fees', 'expense', '52', false, 94, 'car_dealership'),
('5203', 'إهلاك الأصول الثابتة', 'Depreciation Expense', 'expense', '52', false, 95, 'car_dealership'),
('53', 'المصروفات المالية', 'Financial Expenses', 'expense', '5', true, 96, 'car_dealership'),
('5301', 'فوائد القروض', 'Loan Interest', 'expense', '53', false, 97, 'car_dealership'),
('5302', 'رسوم بنكية', 'Bank Charges', 'expense', '53', false, 98, 'car_dealership'),
('5303', 'خسائر تحويل عملات', 'Foreign Exchange Losses', 'expense', '53', false, 99, 'car_dealership'),

-- =====================================================
-- CONSTRUCTION - شجرة حسابات شركات المقاولات
-- =====================================================
('1', 'الأصول', 'Assets', 'asset', NULL, true, 1, 'construction'),
('11', 'الأصول المتداولة', 'Current Assets', 'asset', '1', true, 2, 'construction'),
('1101', 'الصندوق', 'Cash', 'asset', '11', false, 3, 'construction'),
('1102', 'البنك', 'Bank', 'asset', '11', false, 4, 'construction'),
('1103', 'شيكات تحت التحصيل', 'Checks Under Collection', 'asset', '11', false, 5, 'construction'),
('12', 'الذمم المدينة', 'Receivables', 'asset', '1', true, 6, 'construction'),
('1201', 'ذمم العملاء', 'Customer Receivables', 'asset', '12', false, 7, 'construction'),
('1202', 'مستخلصات تحت التحصيل', 'Progress Billings Receivable', 'asset', '12', false, 8, 'construction'),
('1203', 'عهد المشاريع', 'Project Custodies', 'asset', '12', false, 9, 'construction'),
('1204', 'أوراق قبض', 'Notes Receivable', 'asset', '12', false, 10, 'construction'),
('1205', 'تأمينات لدى الغير', 'Deposits with Others', 'asset', '12', false, 11, 'construction'),
('13', 'المخزون', 'Inventory', 'asset', '1', true, 12, 'construction'),
('1301', 'مواد البناء', 'Construction Materials', 'asset', '13', false, 13, 'construction'),
('1302', 'حديد وأسمنت', 'Iron & Cement', 'asset', '13', false, 14, 'construction'),
('1303', 'أدوات ومعدات صغيرة', 'Tools & Small Equipment', 'asset', '13', false, 15, 'construction'),
('1304', 'مواد كهربائية وسباكة', 'Electrical & Plumbing Materials', 'asset', '13', false, 16, 'construction'),
('14', 'الأصول الثابتة', 'Fixed Assets', 'asset', '1', true, 17, 'construction'),
('1401', 'معدات ثقيلة', 'Heavy Equipment', 'asset', '14', false, 18, 'construction'),
('1402', 'سقالات وروافع', 'Scaffolding & Cranes', 'asset', '14', false, 19, 'construction'),
('1403', 'سيارات وشاحنات', 'Vehicles & Trucks', 'asset', '14', false, 20, 'construction'),
('1404', 'خلاطات ومولدات', 'Mixers & Generators', 'asset', '14', false, 21, 'construction'),
('1405', 'مباني وإنشاءات', 'Buildings', 'asset', '14', false, 22, 'construction'),
('1406', 'أثاث ومعدات مكاتب', 'Office Furniture & Equipment', 'asset', '14', false, 23, 'construction'),
('1407', 'أجهزة حاسب', 'Computer Equipment', 'asset', '14', false, 24, 'construction'),
('1408', 'مجمع الإهلاك', 'Accumulated Depreciation', 'asset', '14', false, 25, 'construction'),
('15', 'أعمال تحت التنفيذ', 'Work in Progress', 'asset', '1', true, 26, 'construction'),
('1501', 'مشاريع قيد التنفيذ', 'Projects in Progress', 'asset', '15', false, 27, 'construction'),
('1502', 'مشاريع الصيانة', 'Maintenance Projects', 'asset', '15', false, 28, 'construction'),
('16', 'مصروفات مدفوعة مقدماً', 'Prepaid Expenses', 'asset', '1', true, 29, 'construction'),
('1601', 'إيجار مدفوع مقدماً', 'Prepaid Rent', 'asset', '16', false, 30, 'construction'),
('1602', 'تأمين مدفوع مقدماً', 'Prepaid Insurance', 'asset', '16', false, 31, 'construction'),
-- الالتزامات
('2', 'الالتزامات', 'Liabilities', 'liability', NULL, true, 40, 'construction'),
('21', 'الالتزامات المتداولة', 'Current Liabilities', 'liability', '2', true, 41, 'construction'),
('2101', 'الموردون', 'Suppliers', 'liability', '21', false, 42, 'construction'),
('2102', 'مقاولو الباطن', 'Subcontractors', 'liability', '21', false, 43, 'construction'),
('2103', 'ضريبة القيمة المضافة', 'VAT Payable', 'liability', '21', false, 44, 'construction'),
('2104', 'أوراق دفع', 'Notes Payable', 'liability', '21', false, 45, 'construction'),
('2105', 'رواتب مستحقة', 'Accrued Salaries', 'liability', '21', false, 46, 'construction'),
('2106', 'مصروفات مستحقة', 'Accrued Expenses', 'liability', '21', false, 47, 'construction'),
('2107', 'دفعات مقدمة من العملاء', 'Customer Advance Payments', 'liability', '21', false, 48, 'construction'),
('2108', 'محتجزات ضمان', 'Retention Money', 'liability', '21', false, 49, 'construction'),
('2109', 'تأمين ابتدائي', 'Preliminary Insurance', 'liability', '21', false, 50, 'construction'),
('2110', 'تأمين نهائي', 'Final Insurance', 'liability', '21', false, 51, 'construction'),
('2111', 'تأمينات اجتماعية مستحقة', 'Social Insurance Payable', 'liability', '21', false, 52, 'construction'),
('22', 'الالتزامات طويلة الأجل', 'Long-term Liabilities', 'liability', '2', true, 53, 'construction'),
('2201', 'قروض بنكية طويلة الأجل', 'Long-term Bank Loans', 'liability', '22', false, 54, 'construction'),
('2202', 'خطابات ضمان', 'Letters of Guarantee', 'liability', '22', false, 55, 'construction'),
-- حقوق الملكية
('3', 'حقوق الملكية', 'Equity', 'equity', NULL, true, 60, 'construction'),
('31', 'رأس المال', 'Capital', 'equity', '3', true, 61, 'construction'),
('3101', 'رأس المال المدفوع', 'Paid-in Capital', 'equity', '31', false, 62, 'construction'),
('3102', 'جاري الشريك', 'Partner Current Account', 'equity', '31', false, 63, 'construction'),
('32', 'الاحتياطيات والأرباح', 'Reserves & Earnings', 'equity', '3', true, 64, 'construction'),
('3201', 'الأرباح المحتجزة', 'Retained Earnings', 'equity', '32', false, 65, 'construction'),
('3202', 'الاحتياطي النظامي', 'Legal Reserve', 'equity', '32', false, 66, 'construction'),
('3203', 'أرباح العام', 'Current Year Profit', 'equity', '32', false, 67, 'construction'),
-- الإيرادات
('4', 'الإيرادات', 'Revenue', 'revenue', NULL, true, 70, 'construction'),
('41', 'إيرادات المقاولات', 'Construction Revenue', 'revenue', '4', true, 71, 'construction'),
('4101', 'إيرادات المشاريع', 'Project Revenue', 'revenue', '41', false, 72, 'construction'),
('4102', 'إيرادات الصيانة', 'Maintenance Revenue', 'revenue', '41', false, 73, 'construction'),
('4103', 'إيرادات الاستشارات', 'Consulting Revenue', 'revenue', '41', false, 74, 'construction'),
('4104', 'إيرادات تأجير المعدات', 'Equipment Rental Revenue', 'revenue', '41', false, 75, 'construction'),
('42', 'إيرادات أخرى', 'Other Revenue', 'revenue', '4', true, 76, 'construction'),
('4201', 'خصم مكتسب', 'Purchase Discounts', 'revenue', '42', false, 77, 'construction'),
('4202', 'إيرادات متنوعة', 'Miscellaneous Revenue', 'revenue', '42', false, 78, 'construction'),
-- تكلفة المشاريع
('45', 'تكلفة المشاريع', 'Project Costs', 'expense', '4', true, 79, 'construction'),
('4501', 'مواد بناء مستخدمة', 'Construction Materials Used', 'expense', '45', false, 80, 'construction'),
('4502', 'أجور عمال المشاريع', 'Project Labor Wages', 'expense', '45', false, 81, 'construction'),
('4503', 'تكلفة مقاولي الباطن', 'Subcontractor Costs', 'expense', '45', false, 82, 'construction'),
('4504', 'مصاريف نقل مواد', 'Material Transport Costs', 'expense', '45', false, 83, 'construction'),
('4505', 'إيجار معدات', 'Equipment Rental', 'expense', '45', false, 84, 'construction'),
-- المصروفات
('5', 'المصروفات', 'Expenses', 'expense', NULL, true, 90, 'construction'),
('51', 'المصروفات التشغيلية', 'Operating Expenses', 'expense', '5', true, 91, 'construction'),
('5101', 'رواتب وأجور', 'Salaries & Wages', 'expense', '51', false, 92, 'construction'),
('5102', 'إيجار المكاتب والمواقع', 'Office & Site Rent', 'expense', '51', false, 93, 'construction'),
('5103', 'كهرباء ومياه', 'Electricity & Water', 'expense', '51', false, 94, 'construction'),
('5104', 'صيانة المعدات', 'Equipment Maintenance', 'expense', '51', false, 95, 'construction'),
('5105', 'وقود ومحروقات', 'Fuel & Petroleum', 'expense', '51', false, 96, 'construction'),
('5106', 'تأمين عمال ومعدات', 'Workers & Equipment Insurance', 'expense', '51', false, 97, 'construction'),
('5107', 'أدوات سلامة مهنية', 'Safety Equipment', 'expense', '51', false, 98, 'construction'),
('5108', 'رسوم حكومية وتراخيص', 'Government Fees & Licenses', 'expense', '51', false, 99, 'construction'),
('52', 'المصروفات الإدارية', 'Administrative Expenses', 'expense', '5', true, 100, 'construction'),
('5201', 'مصاريف إدارية عامة', 'General Admin Expenses', 'expense', '52', false, 101, 'construction'),
('5202', 'استشارات هندسية ومحاسبية', 'Engineering & Accounting Fees', 'expense', '52', false, 102, 'construction'),
('5203', 'إهلاك الأصول الثابتة', 'Depreciation Expense', 'expense', '52', false, 103, 'construction'),
('5204', 'اتصالات وإنترنت', 'Telecom & Internet', 'expense', '52', false, 104, 'construction'),
('5205', 'أدوات مكتبية', 'Office Supplies', 'expense', '52', false, 105, 'construction'),
('53', 'المصروفات المالية', 'Financial Expenses', 'expense', '5', true, 106, 'construction'),
('5301', 'فوائد القروض', 'Loan Interest', 'expense', '53', false, 107, 'construction'),
('5302', 'رسوم بنكية', 'Bank Charges', 'expense', '53', false, 108, 'construction'),
('5303', 'رسوم خطابات ضمان', 'Guarantee Letter Fees', 'expense', '53', false, 109, 'construction'),

-- =====================================================
-- RESTAURANT - شجرة حسابات المطاعم
-- =====================================================
('1', 'الأصول', 'Assets', 'asset', NULL, true, 1, 'restaurant'),
('11', 'الأصول المتداولة', 'Current Assets', 'asset', '1', true, 2, 'restaurant'),
('1101', 'الصندوق', 'Cash', 'asset', '11', false, 3, 'restaurant'),
('1102', 'البنك', 'Bank', 'asset', '11', false, 4, 'restaurant'),
('1103', 'مبيعات نقدية POS', 'POS Cash Sales', 'asset', '11', false, 5, 'restaurant'),
('1104', 'مبيعات بطاقات ائتمان', 'Credit Card Sales', 'asset', '11', false, 6, 'restaurant'),
('12', 'الذمم المدينة', 'Receivables', 'asset', '1', true, 7, 'restaurant'),
('1201', 'العملاء', 'Customers', 'asset', '12', false, 8, 'restaurant'),
('1202', 'تطبيقات التوصيل', 'Delivery App Receivables', 'asset', '12', false, 9, 'restaurant'),
('1203', 'أمانات وتأمينات مدينة', 'Deposits & Guarantees', 'asset', '12', false, 10, 'restaurant'),
('13', 'المخزون', 'Inventory', 'asset', '1', true, 11, 'restaurant'),
('1301', 'مخزون المواد الغذائية', 'Food Materials Inventory', 'asset', '13', false, 12, 'restaurant'),
('1302', 'مخزون المشروبات', 'Beverages Inventory', 'asset', '13', false, 13, 'restaurant'),
('1303', 'مواد التعبئة والتغليف', 'Packaging Materials', 'asset', '13', false, 14, 'restaurant'),
('1304', 'مخزون مواد النظافة', 'Cleaning Supplies', 'asset', '13', false, 15, 'restaurant'),
('1305', 'مخزون أدوات المطبخ', 'Kitchen Utensils', 'asset', '13', false, 16, 'restaurant'),
('14', 'الأصول الثابتة', 'Fixed Assets', 'asset', '1', true, 17, 'restaurant'),
('1401', 'معدات المطبخ (أفران، شوايات)', 'Kitchen Equipment', 'asset', '14', false, 18, 'restaurant'),
('1402', 'أثاث وتجهيزات الصالة', 'Dining Hall Furniture', 'asset', '14', false, 19, 'restaurant'),
('1403', 'معدات التبريد والتجميد', 'Refrigeration Equipment', 'asset', '14', false, 20, 'restaurant'),
('1404', 'أنظمة نقاط البيع', 'POS Systems', 'asset', '14', false, 21, 'restaurant'),
('1405', 'سيارات التوصيل', 'Delivery Vehicles', 'asset', '14', false, 22, 'restaurant'),
('1406', 'ديكورات وتحسينات', 'Decor & Improvements', 'asset', '14', false, 23, 'restaurant'),
('1407', 'أنظمة تكييف وتهوية', 'HVAC Systems', 'asset', '14', false, 24, 'restaurant'),
('1408', 'مجمع الإهلاك', 'Accumulated Depreciation', 'asset', '14', false, 25, 'restaurant'),
('15', 'مصروفات مدفوعة مقدماً', 'Prepaid Expenses', 'asset', '1', true, 26, 'restaurant'),
('1501', 'إيجار مدفوع مقدماً', 'Prepaid Rent', 'asset', '15', false, 27, 'restaurant'),
('1502', 'تأمين مدفوع مقدماً', 'Prepaid Insurance', 'asset', '15', false, 28, 'restaurant'),
-- الالتزامات
('2', 'الالتزامات', 'Liabilities', 'liability', NULL, true, 30, 'restaurant'),
('21', 'الالتزامات المتداولة', 'Current Liabilities', 'liability', '2', true, 31, 'restaurant'),
('2101', 'موردو المواد الغذائية', 'Food Suppliers', 'liability', '21', false, 32, 'restaurant'),
('2102', 'موردو المشروبات', 'Beverage Suppliers', 'liability', '21', false, 33, 'restaurant'),
('2103', 'ضريبة القيمة المضافة', 'VAT Payable', 'liability', '21', false, 34, 'restaurant'),
('2104', 'رواتب مستحقة', 'Accrued Salaries', 'liability', '21', false, 35, 'restaurant'),
('2105', 'مصروفات مستحقة', 'Accrued Expenses', 'liability', '21', false, 36, 'restaurant'),
('2106', 'أمانات تأمين للموظفين', 'Employee Security Deposits', 'liability', '21', false, 37, 'restaurant'),
('2107', 'تأمينات اجتماعية مستحقة', 'Social Insurance Payable', 'liability', '21', false, 38, 'restaurant'),
('22', 'الالتزامات طويلة الأجل', 'Long-term Liabilities', 'liability', '2', true, 39, 'restaurant'),
('2201', 'قروض بنكية طويلة الأجل', 'Long-term Bank Loans', 'liability', '22', false, 40, 'restaurant'),
('2202', 'إيجار تمويلي', 'Finance Lease', 'liability', '22', false, 41, 'restaurant'),
-- حقوق الملكية
('3', 'حقوق الملكية', 'Equity', 'equity', NULL, true, 50, 'restaurant'),
('31', 'رأس المال', 'Capital', 'equity', '3', true, 51, 'restaurant'),
('3101', 'رأس المال المدفوع', 'Paid-in Capital', 'equity', '31', false, 52, 'restaurant'),
('3102', 'جاري الشريك', 'Partner Current Account', 'equity', '31', false, 53, 'restaurant'),
('32', 'الاحتياطيات والأرباح', 'Reserves & Earnings', 'equity', '3', true, 54, 'restaurant'),
('3201', 'الأرباح المحتجزة', 'Retained Earnings', 'equity', '32', false, 55, 'restaurant'),
('3202', 'الاحتياطي النظامي', 'Legal Reserve', 'equity', '32', false, 56, 'restaurant'),
('3203', 'أرباح العام', 'Current Year Profit', 'equity', '32', false, 57, 'restaurant'),
-- الإيرادات
('4', 'الإيرادات', 'Revenue', 'revenue', NULL, true, 60, 'restaurant'),
('41', 'إيرادات المبيعات', 'Sales Revenue', 'revenue', '4', true, 61, 'restaurant'),
('4101', 'مبيعات المأكولات', 'Food Sales', 'revenue', '41', false, 62, 'restaurant'),
('4102', 'مبيعات المشروبات', 'Beverage Sales', 'revenue', '41', false, 63, 'restaurant'),
('4103', 'إيرادات التوصيل', 'Delivery Revenue', 'revenue', '41', false, 64, 'restaurant'),
('4104', 'إيرادات المناسبات والحفلات', 'Events & Catering Revenue', 'revenue', '41', false, 65, 'restaurant'),
('4105', 'رسوم الخدمة', 'Service Charges', 'revenue', '41', false, 66, 'restaurant'),
('42', 'إيرادات أخرى', 'Other Revenue', 'revenue', '4', true, 67, 'restaurant'),
('4201', 'إيرادات متنوعة', 'Miscellaneous Revenue', 'revenue', '42', false, 68, 'restaurant'),
-- تكلفة البضاعة المباعة
('45', 'تكلفة البضاعة المباعة', 'Cost of Goods Sold', 'expense', '4', true, 69, 'restaurant'),
('4501', 'تكلفة المواد الغذائية', 'Food Cost', 'expense', '45', false, 70, 'restaurant'),
('4502', 'تكلفة المشروبات', 'Beverage Cost', 'expense', '45', false, 71, 'restaurant'),
('4503', 'تكلفة التغليف', 'Packaging Cost', 'expense', '45', false, 72, 'restaurant'),
('4504', 'هدر غذائي', 'Food Waste', 'expense', '45', false, 73, 'restaurant'),
-- المصروفات
('5', 'المصروفات', 'Expenses', 'expense', NULL, true, 80, 'restaurant'),
('51', 'المصروفات التشغيلية', 'Operating Expenses', 'expense', '5', true, 81, 'restaurant'),
('5101', 'رواتب الطهاة', 'Chef Salaries', 'expense', '51', false, 82, 'restaurant'),
('5102', 'رواتب العاملين', 'Staff Salaries', 'expense', '51', false, 83, 'restaurant'),
('5103', 'رواتب سائقي التوصيل', 'Delivery Driver Salaries', 'expense', '51', false, 84, 'restaurant'),
('5104', 'إيجار المطعم', 'Restaurant Rent', 'expense', '51', false, 85, 'restaurant'),
('5105', 'كهرباء', 'Electricity', 'expense', '51', false, 86, 'restaurant'),
('5106', 'مياه', 'Water', 'expense', '51', false, 87, 'restaurant'),
('5107', 'غاز', 'Gas', 'expense', '51', false, 88, 'restaurant'),
('5108', 'صيانة معدات المطبخ', 'Kitchen Equipment Maintenance', 'expense', '51', false, 89, 'restaurant'),
('5109', 'مواد نظافة وتعقيم', 'Cleaning & Sanitation', 'expense', '51', false, 90, 'restaurant'),
('5110', 'تسويق وإعلان', 'Marketing & Advertising', 'expense', '51', false, 91, 'restaurant'),
('5111', 'عمولات تطبيقات التوصيل', 'Delivery App Commissions', 'expense', '51', false, 92, 'restaurant'),
('5112', 'مصاريف بنكية POS', 'POS Bank Fees', 'expense', '51', false, 93, 'restaurant'),
('52', 'المصروفات الإدارية', 'Administrative Expenses', 'expense', '5', true, 94, 'restaurant'),
('5201', 'مصاريف إدارية عامة', 'General Admin Expenses', 'expense', '52', false, 95, 'restaurant'),
('5202', 'رسوم حكومية وتراخيص صحية', 'Government & Health License Fees', 'expense', '52', false, 96, 'restaurant'),
('5203', 'إهلاك الأصول الثابتة', 'Depreciation Expense', 'expense', '52', false, 97, 'restaurant'),
('5204', 'تأمين المطعم', 'Restaurant Insurance', 'expense', '52', false, 98, 'restaurant'),
('5205', 'اتصالات وإنترنت', 'Telecom & Internet', 'expense', '52', false, 99, 'restaurant'),
('53', 'المصروفات المالية', 'Financial Expenses', 'expense', '5', true, 100, 'restaurant'),
('5301', 'فوائد القروض', 'Loan Interest', 'expense', '53', false, 101, 'restaurant'),
('5302', 'رسوم بنكية', 'Bank Charges', 'expense', '53', false, 102, 'restaurant'),

-- =====================================================
-- GENERAL TRADING - شجرة حسابات التجارة العامة
-- =====================================================
('1', 'الأصول', 'Assets', 'asset', NULL, true, 1, 'general_trading'),
('11', 'الأصول المتداولة', 'Current Assets', 'asset', '1', true, 2, 'general_trading'),
('1101', 'الصندوق', 'Cash', 'asset', '11', false, 3, 'general_trading'),
('1102', 'البنك', 'Bank', 'asset', '11', false, 4, 'general_trading'),
('1103', 'نقاط البيع', 'POS', 'asset', '11', false, 5, 'general_trading'),
('1104', 'شيكات تحت التحصيل', 'Checks Under Collection', 'asset', '11', false, 6, 'general_trading'),
('12', 'الذمم المدينة', 'Receivables', 'asset', '1', true, 7, 'general_trading'),
('1201', 'العملاء', 'Customers', 'asset', '12', false, 8, 'general_trading'),
('1202', 'أوراق قبض', 'Notes Receivable', 'asset', '12', false, 9, 'general_trading'),
('1203', 'ذمم مدينة أخرى', 'Other Receivables', 'asset', '12', false, 10, 'general_trading'),
('13', 'المخزون', 'Inventory', 'asset', '1', true, 11, 'general_trading'),
('1301', 'مخزون البضائع', 'Merchandise Inventory', 'asset', '13', false, 12, 'general_trading'),
('1302', 'بضائع بالطريق', 'Goods in Transit', 'asset', '13', false, 13, 'general_trading'),
('1303', 'مخزون مواد تغليف', 'Packaging Materials', 'asset', '13', false, 14, 'general_trading'),
('14', 'الأصول الثابتة', 'Fixed Assets', 'asset', '1', true, 15, 'general_trading'),
('1401', 'مباني ومعارض', 'Buildings & Showrooms', 'asset', '14', false, 16, 'general_trading'),
('1402', 'أثاث وتجهيزات', 'Furniture & Fixtures', 'asset', '14', false, 17, 'general_trading'),
('1403', 'أجهزة حاسب', 'Computer Equipment', 'asset', '14', false, 18, 'general_trading'),
('1404', 'سيارات نقل', 'Transport Vehicles', 'asset', '14', false, 19, 'general_trading'),
('1405', 'مجمع الإهلاك', 'Accumulated Depreciation', 'asset', '14', false, 20, 'general_trading'),
('15', 'مصروفات مدفوعة مقدماً', 'Prepaid Expenses', 'asset', '1', true, 21, 'general_trading'),
('1501', 'إيجار مدفوع مقدماً', 'Prepaid Rent', 'asset', '15', false, 22, 'general_trading'),
('1502', 'تأمين مدفوع مقدماً', 'Prepaid Insurance', 'asset', '15', false, 23, 'general_trading'),
-- الالتزامات
('2', 'الالتزامات', 'Liabilities', 'liability', NULL, true, 30, 'general_trading'),
('21', 'الالتزامات المتداولة', 'Current Liabilities', 'liability', '2', true, 31, 'general_trading'),
('2101', 'الموردون', 'Suppliers', 'liability', '21', false, 32, 'general_trading'),
('2102', 'ضريبة القيمة المضافة', 'VAT Payable', 'liability', '21', false, 33, 'general_trading'),
('2103', 'أوراق دفع', 'Notes Payable', 'liability', '21', false, 34, 'general_trading'),
('2104', 'رواتب مستحقة', 'Accrued Salaries', 'liability', '21', false, 35, 'general_trading'),
('2105', 'مصروفات مستحقة', 'Accrued Expenses', 'liability', '21', false, 36, 'general_trading'),
('2106', 'دفعات مقدمة من العملاء', 'Customer Advance Payments', 'liability', '21', false, 37, 'general_trading'),
('2107', 'تأمينات اجتماعية مستحقة', 'Social Insurance Payable', 'liability', '21', false, 38, 'general_trading'),
('22', 'الالتزامات طويلة الأجل', 'Long-term Liabilities', 'liability', '2', true, 39, 'general_trading'),
('2201', 'قروض بنكية طويلة الأجل', 'Long-term Bank Loans', 'liability', '22', false, 40, 'general_trading'),
-- حقوق الملكية
('3', 'حقوق الملكية', 'Equity', 'equity', NULL, true, 50, 'general_trading'),
('31', 'رأس المال', 'Capital', 'equity', '3', true, 51, 'general_trading'),
('3101', 'رأس المال المدفوع', 'Paid-in Capital', 'equity', '31', false, 52, 'general_trading'),
('3102', 'جاري الشريك', 'Partner Current Account', 'equity', '31', false, 53, 'general_trading'),
('32', 'الاحتياطيات والأرباح', 'Reserves & Earnings', 'equity', '3', true, 54, 'general_trading'),
('3201', 'الأرباح المحتجزة', 'Retained Earnings', 'equity', '32', false, 55, 'general_trading'),
('3202', 'الاحتياطي النظامي', 'Legal Reserve', 'equity', '32', false, 56, 'general_trading'),
('3203', 'أرباح العام', 'Current Year Profit', 'equity', '32', false, 57, 'general_trading'),
-- الإيرادات
('4', 'الإيرادات', 'Revenue', 'revenue', NULL, true, 60, 'general_trading'),
('41', 'إيرادات المبيعات', 'Sales Revenue', 'revenue', '4', true, 61, 'general_trading'),
('4101', 'مبيعات بضائع', 'Merchandise Sales', 'revenue', '41', false, 62, 'general_trading'),
('4102', 'مبيعات جملة', 'Wholesale Sales', 'revenue', '41', false, 63, 'general_trading'),
('4103', 'مبيعات تجزئة', 'Retail Sales', 'revenue', '41', false, 64, 'general_trading'),
('42', 'إيرادات أخرى', 'Other Revenue', 'revenue', '4', true, 65, 'general_trading'),
('4201', 'خصم مكتسب', 'Purchase Discounts', 'revenue', '42', false, 66, 'general_trading'),
('4202', 'إيرادات عمولات', 'Commission Revenue', 'revenue', '42', false, 67, 'general_trading'),
('4203', 'إيرادات متنوعة', 'Miscellaneous Revenue', 'revenue', '42', false, 68, 'general_trading'),
-- تكلفة المبيعات
('45', 'تكلفة المبيعات', 'Cost of Sales', 'expense', '4', true, 69, 'general_trading'),
('4501', 'تكلفة البضاعة المباعة', 'Cost of Goods Sold', 'expense', '45', false, 70, 'general_trading'),
('4502', 'مصاريف شحن ونقل', 'Shipping & Transport', 'expense', '45', false, 71, 'general_trading'),
('4503', 'رسوم جمركية', 'Customs Duties', 'expense', '45', false, 72, 'general_trading'),
('4504', 'تكلفة تغليف', 'Packaging Cost', 'expense', '45', false, 73, 'general_trading'),
-- المصروفات
('5', 'المصروفات', 'Expenses', 'expense', NULL, true, 80, 'general_trading'),
('51', 'المصروفات التشغيلية', 'Operating Expenses', 'expense', '5', true, 81, 'general_trading'),
('5101', 'رواتب وأجور', 'Salaries & Wages', 'expense', '51', false, 82, 'general_trading'),
('5102', 'إيجار المحل/المستودع', 'Store/Warehouse Rent', 'expense', '51', false, 83, 'general_trading'),
('5103', 'كهرباء ومياه', 'Electricity & Water', 'expense', '51', false, 84, 'general_trading'),
('5104', 'صيانة ونظافة', 'Maintenance & Cleaning', 'expense', '51', false, 85, 'general_trading'),
('5105', 'تسويق وإعلان', 'Marketing & Advertising', 'expense', '51', false, 86, 'general_trading'),
('5106', 'مصاريف نقل وتوصيل', 'Transport & Delivery', 'expense', '51', false, 87, 'general_trading'),
('5107', 'تأمين', 'Insurance', 'expense', '51', false, 88, 'general_trading'),
('5108', 'رسوم حكومية وتراخيص', 'Government Fees & Licenses', 'expense', '51', false, 89, 'general_trading'),
('52', 'المصروفات الإدارية', 'Administrative Expenses', 'expense', '5', true, 90, 'general_trading'),
('5201', 'مصاريف إدارية عامة', 'General Admin Expenses', 'expense', '52', false, 91, 'general_trading'),
('5202', 'استشارات قانونية ومحاسبية', 'Legal & Accounting Fees', 'expense', '52', false, 92, 'general_trading'),
('5203', 'إهلاك الأصول الثابتة', 'Depreciation Expense', 'expense', '52', false, 93, 'general_trading'),
('5204', 'اتصالات وإنترنت', 'Telecom & Internet', 'expense', '52', false, 94, 'general_trading'),
('5205', 'أدوات مكتبية', 'Office Supplies', 'expense', '52', false, 95, 'general_trading'),
('53', 'المصروفات المالية', 'Financial Expenses', 'expense', '5', true, 96, 'general_trading'),
('5301', 'فوائد القروض', 'Loan Interest', 'expense', '53', false, 97, 'general_trading'),
('5302', 'رسوم بنكية', 'Bank Charges', 'expense', '53', false, 98, 'general_trading'),
('5303', 'خسائر تحويل عملات', 'Foreign Exchange Losses', 'expense', '53', false, 99, 'general_trading'),

-- =====================================================
-- EXPORT/IMPORT - شجرة حسابات الاستيراد والتصدير
-- =====================================================
('1', 'الأصول', 'Assets', 'asset', NULL, true, 1, 'export_import'),
('11', 'الأصول المتداولة', 'Current Assets', 'asset', '1', true, 2, 'export_import'),
('1101', 'الصندوق', 'Cash', 'asset', '11', false, 3, 'export_import'),
('1102', 'البنك - حساب محلي', 'Bank - Local Account', 'asset', '11', false, 4, 'export_import'),
('1103', 'البنك - حساب أجنبي', 'Bank - Foreign Account', 'asset', '11', false, 5, 'export_import'),
('1104', 'شيكات تحت التحصيل', 'Checks Under Collection', 'asset', '11', false, 6, 'export_import'),
('12', 'الذمم المدينة', 'Receivables', 'asset', '1', true, 7, 'export_import'),
('1201', 'عملاء محليون', 'Local Customers', 'asset', '12', false, 8, 'export_import'),
('1202', 'عملاء خارجيون', 'Foreign Customers', 'asset', '12', false, 9, 'export_import'),
('1203', 'خطابات اعتماد مدينة', 'Letters of Credit Receivable', 'asset', '12', false, 10, 'export_import'),
('1204', 'بضاعة في الطريق', 'Goods in Transit', 'asset', '12', false, 11, 'export_import'),
('1205', 'رسوم مدفوعة مقدماً', 'Prepaid Fees', 'asset', '12', false, 12, 'export_import'),
('13', 'المخزون', 'Inventory', 'asset', '1', true, 13, 'export_import'),
('1301', 'بضاعة في المستودع', 'Warehouse Inventory', 'asset', '13', false, 14, 'export_import'),
('1302', 'بضاعة بالجمارك', 'Goods at Customs', 'asset', '13', false, 15, 'export_import'),
('1303', 'بضاعة في الميناء', 'Goods at Port', 'asset', '13', false, 16, 'export_import'),
('1304', 'بضاعة في المنطقة الحرة', 'Free Zone Inventory', 'asset', '13', false, 17, 'export_import'),
('14', 'الأصول الثابتة', 'Fixed Assets', 'asset', '1', true, 18, 'export_import'),
('1401', 'مستودعات', 'Warehouses', 'asset', '14', false, 19, 'export_import'),
('1402', 'سيارات ونقل', 'Vehicles & Transport', 'asset', '14', false, 20, 'export_import'),
('1403', 'أثاث ومعدات مكتبية', 'Office Furniture & Equipment', 'asset', '14', false, 21, 'export_import'),
('1404', 'أجهزة حاسب', 'Computer Equipment', 'asset', '14', false, 22, 'export_import'),
('1405', 'مجمع الإهلاك', 'Accumulated Depreciation', 'asset', '14', false, 23, 'export_import'),
('15', 'مصروفات مدفوعة مقدماً', 'Prepaid Expenses', 'asset', '1', true, 24, 'export_import'),
('1501', 'تأمين شحن مدفوع مقدماً', 'Prepaid Shipping Insurance', 'asset', '15', false, 25, 'export_import'),
('1502', 'رسوم جمركية مدفوعة مقدماً', 'Prepaid Customs Duties', 'asset', '15', false, 26, 'export_import'),
-- الالتزامات
('2', 'الالتزامات', 'Liabilities', 'liability', NULL, true, 30, 'export_import'),
('21', 'الالتزامات المتداولة', 'Current Liabilities', 'liability', '2', true, 31, 'export_import'),
('2101', 'موردون محليون', 'Local Suppliers', 'liability', '21', false, 32, 'export_import'),
('2102', 'موردون خارجيون', 'Foreign Suppliers', 'liability', '21', false, 33, 'export_import'),
('2103', 'خطابات اعتماد دائنة', 'Letters of Credit Payable', 'liability', '21', false, 34, 'export_import'),
('2104', 'ضريبة القيمة المضافة', 'VAT Payable', 'liability', '21', false, 35, 'export_import'),
('2105', 'رسوم جمركية مستحقة', 'Customs Duties Payable', 'liability', '21', false, 36, 'export_import'),
('2106', 'رواتب مستحقة', 'Accrued Salaries', 'liability', '21', false, 37, 'export_import'),
('2107', 'مصروفات مستحقة', 'Accrued Expenses', 'liability', '21', false, 38, 'export_import'),
('2108', 'تأمينات اجتماعية مستحقة', 'Social Insurance Payable', 'liability', '21', false, 39, 'export_import'),
('22', 'الالتزامات طويلة الأجل', 'Long-term Liabilities', 'liability', '2', true, 40, 'export_import'),
('2201', 'قروض بنكية طويلة الأجل', 'Long-term Bank Loans', 'liability', '22', false, 41, 'export_import'),
('2202', 'تسهيلات تمويل تجارة', 'Trade Finance Facilities', 'liability', '22', false, 42, 'export_import'),
-- حقوق الملكية
('3', 'حقوق الملكية', 'Equity', 'equity', NULL, true, 50, 'export_import'),
('31', 'رأس المال', 'Capital', 'equity', '3', true, 51, 'export_import'),
('3101', 'رأس المال المدفوع', 'Paid-in Capital', 'equity', '31', false, 52, 'export_import'),
('3102', 'جاري الشريك', 'Partner Current Account', 'equity', '31', false, 53, 'export_import'),
('32', 'الاحتياطيات والأرباح', 'Reserves & Earnings', 'equity', '3', true, 54, 'export_import'),
('3201', 'الأرباح المحتجزة', 'Retained Earnings', 'equity', '32', false, 55, 'export_import'),
('3202', 'الاحتياطي النظامي', 'Legal Reserve', 'equity', '32', false, 56, 'export_import'),
('3203', 'أرباح العام', 'Current Year Profit', 'equity', '32', false, 57, 'export_import'),
-- الإيرادات
('4', 'الإيرادات', 'Revenue', 'revenue', NULL, true, 60, 'export_import'),
('41', 'إيرادات الصادرات', 'Export Revenue', 'revenue', '4', true, 61, 'export_import'),
('4101', 'مبيعات صادرات', 'Export Sales', 'revenue', '41', false, 62, 'export_import'),
('4102', 'مبيعات محلية', 'Local Sales', 'revenue', '41', false, 63, 'export_import'),
('4103', 'عمولات وساطة تجارية', 'Trade Brokerage Commissions', 'revenue', '41', false, 64, 'export_import'),
('42', 'إيرادات أخرى', 'Other Revenue', 'revenue', '4', true, 65, 'export_import'),
('4201', 'أرباح فروقات عملات', 'Foreign Exchange Gains', 'revenue', '42', false, 66, 'export_import'),
('4202', 'خصم مكتسب', 'Purchase Discounts', 'revenue', '42', false, 67, 'export_import'),
('4203', 'إيرادات متنوعة', 'Miscellaneous Revenue', 'revenue', '42', false, 68, 'export_import'),
-- تكلفة المبيعات
('45', 'تكلفة المبيعات', 'Cost of Sales', 'expense', '4', true, 69, 'export_import'),
('4501', 'تكلفة البضاعة المستوردة', 'Cost of Imported Goods', 'expense', '45', false, 70, 'export_import'),
('4502', 'رسوم جمركية', 'Customs Duties', 'expense', '45', false, 71, 'export_import'),
('4503', 'مصاريف شحن دولي', 'International Shipping', 'expense', '45', false, 72, 'export_import'),
('4504', 'تأمين شحن', 'Shipping Insurance', 'expense', '45', false, 73, 'export_import'),
('4505', 'رسوم تخليص جمركي', 'Customs Clearance Fees', 'expense', '45', false, 74, 'export_import'),
('4506', 'مصاريف أرضيات وتخزين', 'Demurrage & Storage', 'expense', '45', false, 75, 'export_import'),
-- المصروفات
('5', 'المصروفات', 'Expenses', 'expense', NULL, true, 80, 'export_import'),
('51', 'المصروفات التشغيلية', 'Operating Expenses', 'expense', '5', true, 81, 'export_import'),
('5101', 'رواتب وأجور', 'Salaries & Wages', 'expense', '51', false, 82, 'export_import'),
('5102', 'إيجار المكاتب والمستودعات', 'Office & Warehouse Rent', 'expense', '51', false, 83, 'export_import'),
('5103', 'كهرباء ومياه', 'Electricity & Water', 'expense', '51', false, 84, 'export_import'),
('5104', 'صيانة', 'Maintenance', 'expense', '51', false, 85, 'export_import'),
('5105', 'تسويق وإعلان', 'Marketing & Advertising', 'expense', '51', false, 86, 'export_import'),
('5106', 'مصاريف سفر وتنقل', 'Travel Expenses', 'expense', '51', false, 87, 'export_import'),
('5107', 'تأمين', 'Insurance', 'expense', '51', false, 88, 'export_import'),
('5108', 'رسوم حكومية وتراخيص', 'Government Fees & Licenses', 'expense', '51', false, 89, 'export_import'),
('52', 'المصروفات الإدارية', 'Administrative Expenses', 'expense', '5', true, 90, 'export_import'),
('5201', 'مصاريف إدارية عامة', 'General Admin Expenses', 'expense', '52', false, 91, 'export_import'),
('5202', 'استشارات قانونية ومحاسبية', 'Legal & Accounting Fees', 'expense', '52', false, 92, 'export_import'),
('5203', 'إهلاك الأصول الثابتة', 'Depreciation Expense', 'expense', '52', false, 93, 'export_import'),
('5204', 'اتصالات وإنترنت', 'Telecom & Internet', 'expense', '52', false, 94, 'export_import'),
('5205', 'أدوات مكتبية', 'Office Supplies', 'expense', '52', false, 95, 'export_import'),
('53', 'المصروفات المالية', 'Financial Expenses', 'expense', '5', true, 96, 'export_import'),
('5301', 'فوائد القروض', 'Loan Interest', 'expense', '53', false, 97, 'export_import'),
('5302', 'رسوم بنكية', 'Bank Charges', 'expense', '53', false, 98, 'export_import'),
('5303', 'خسائر تحويل عملات', 'Foreign Exchange Losses', 'expense', '53', false, 99, 'export_import'),
('5304', 'رسوم خطابات اعتماد', 'Letter of Credit Fees', 'expense', '53', false, 100, 'export_import');
