
INSERT INTO public.coa_templates (code, company_type, name, name_en, type, is_header, parent_code, sort_order) VALUES
('1', 'real_estate', 'الأصول', 'Assets', 'asset', true, NULL, 1),
('11', 'real_estate', 'الأصول المتداولة', 'Current Assets', 'asset', true, '1', 2),
('1101', 'real_estate', 'النقدية وما يعادلها', 'Cash & Equivalents', 'asset', false, '11', 3),
('1102', 'real_estate', 'البنوك', 'Banks', 'asset', false, '11', 4),
('1103', 'real_estate', 'ذمم مدينة - عملاء', 'Accounts Receivable', 'asset', false, '11', 5),
('1104', 'real_estate', 'شيكات تحت التحصيل', 'Checks Under Collection', 'asset', false, '11', 6),
('1105', 'real_estate', 'ذمم مدينة أخرى', 'Other Receivables', 'asset', false, '11', 7),
('12', 'real_estate', 'أصول متداولة أخرى', 'Other Current Assets', 'asset', true, '1', 8),
('1201', 'real_estate', 'مصاريف مدفوعة مقدماً', 'Prepaid Expenses', 'asset', false, '12', 9),
('1202', 'real_estate', 'دفعات مقدمة للمقاولين', 'Advance Payments to Contractors', 'asset', false, '12', 10),
('1203', 'real_estate', 'تأمينات مسترده', 'Refundable Deposits', 'asset', false, '12', 11),
('13', 'real_estate', 'مشاريع تحت التطوير', 'Projects Under Development', 'asset', true, '1', 12),
('1301', 'real_estate', 'أراضي المشاريع', 'Project Lands', 'asset', false, '13', 13),
('1302', 'real_estate', 'وحدات تحت الإنشاء', 'Units Under Construction', 'asset', false, '13', 14),
('1303', 'real_estate', 'تكاليف تصاميم هندسية', 'Engineering Design Costs', 'asset', false, '13', 15),
('1304', 'real_estate', 'تكاليف تراخيص ورسوم حكومية', 'Licensing & Government Fees', 'asset', false, '13', 16),
('1305', 'real_estate', 'تكاليف بنية تحتية', 'Infrastructure Costs', 'asset', false, '13', 17),
('14', 'real_estate', 'الأصول الثابتة', 'Fixed Assets', 'asset', true, '1', 18),
('1401', 'real_estate', 'مباني إدارية', 'Administrative Buildings', 'asset', false, '14', 19),
('1402', 'real_estate', 'سيارات ومعدات', 'Vehicles & Equipment', 'asset', false, '14', 20),
('1403', 'real_estate', 'أثاث ومفروشات', 'Furniture & Fixtures', 'asset', false, '14', 21),
('1404', 'real_estate', 'أجهزة حاسب', 'Computers', 'asset', false, '14', 22),
('1405', 'real_estate', 'مجمع الاستهلاك', 'Accumulated Depreciation', 'asset', false, '14', 23),
('2', 'real_estate', 'الالتزامات', 'Liabilities', 'liability', true, NULL, 24),
('21', 'real_estate', 'الالتزامات المتداولة', 'Current Liabilities', 'liability', true, '2', 25),
('2101', 'real_estate', 'ذمم دائنة - موردين ومقاولين', 'Accounts Payable', 'liability', false, '21', 26),
('2102', 'real_estate', 'دفعات مقدمة من العملاء', 'Customer Advance Payments', 'liability', false, '21', 27),
('2103', 'real_estate', 'أقساط مقاولين مستحقة', 'Contractor Installments Payable', 'liability', false, '21', 28),
('2104', 'real_estate', 'ضريبة القيمة المضافة', 'VAT Payable', 'liability', false, '21', 29),
('2105', 'real_estate', 'مصاريف مستحقة', 'Accrued Expenses', 'liability', false, '21', 30),
('2106', 'real_estate', 'رواتب مستحقة', 'Salaries Payable', 'liability', false, '21', 31),
('22', 'real_estate', 'الالتزامات طويلة الأجل', 'Long-term Liabilities', 'liability', true, '2', 32),
('2201', 'real_estate', 'قروض بنكية', 'Bank Loans', 'liability', false, '22', 33),
('2202', 'real_estate', 'تمويل مشاريع', 'Project Financing', 'liability', false, '22', 34),
('3', 'real_estate', 'حقوق الملكية', 'Equity', 'equity', true, NULL, 35),
('3101', 'real_estate', 'رأس المال', 'Capital', 'equity', false, '3', 36),
('3102', 'real_estate', 'مساهمات عينية', 'In-Kind Contributions', 'equity', false, '3', 37),
('3103', 'real_estate', 'أرباح مبقاة', 'Retained Earnings', 'equity', false, '3', 38),
('3104', 'real_estate', 'احتياطي نظامي', 'Statutory Reserve', 'equity', false, '3', 39),
('3105', 'real_estate', 'أرباح / خسائر العام', 'Current Year P&L', 'equity', false, '3', 40),
('4', 'real_estate', 'الإيرادات', 'Revenue', 'revenue', true, NULL, 41),
('4101', 'real_estate', 'إيرادات بيع وحدات عقارية', 'Real Estate Unit Sales', 'revenue', false, '4', 42),
('4102', 'real_estate', 'إيرادات بيع أراضي', 'Land Sales Revenue', 'revenue', false, '4', 43),
('4103', 'real_estate', 'إيرادات إيجارات', 'Rental Income', 'revenue', false, '4', 44),
('4104', 'real_estate', 'إيرادات إدارة أملاك', 'Property Management Income', 'revenue', false, '4', 45),
('4105', 'real_estate', 'إيرادات أخرى', 'Other Revenue', 'revenue', false, '4', 46),
('5', 'real_estate', 'تكلفة المبيعات', 'Cost of Sales', 'expense', true, NULL, 47),
('5101', 'real_estate', 'تكلفة أراضي مباعة', 'Cost of Land Sold', 'expense', false, '5', 48),
('5102', 'real_estate', 'تكلفة إنشاء وحدات مباعة', 'Construction Cost of Units Sold', 'expense', false, '5', 49),
('5103', 'real_estate', 'تكلفة تصاميم هندسية', 'Engineering Design Costs', 'expense', false, '5', 50),
('5104', 'real_estate', 'تكلفة مقاولين من الباطن', 'Subcontractor Costs', 'expense', false, '5', 51),
('5105', 'real_estate', 'تكلفة بنية تحتية مباعة', 'Infrastructure Costs Sold', 'expense', false, '5', 52),
('6', 'real_estate', 'المصاريف التشغيلية', 'Operating Expenses', 'expense', true, NULL, 53),
('61', 'real_estate', 'مصاريف الموقع والمعدات', 'Site & Equipment Expenses', 'expense', true, '6', 54),
('6101', 'real_estate', 'إيجار معدات ورافعات', 'Equipment & Crane Rental', 'expense', false, '61', 55),
('6102', 'real_estate', 'صيانة معدات', 'Equipment Maintenance', 'expense', false, '61', 56),
('6103', 'real_estate', 'حراسة مواقع', 'Site Security', 'expense', false, '61', 57),
('6104', 'real_estate', 'تأمين مشاريع', 'Project Insurance', 'expense', false, '61', 58),
('62', 'real_estate', 'المصاريف الإدارية والعمومية', 'General & Admin Expenses', 'expense', true, '6', 59),
('6201', 'real_estate', 'رواتب وأجور', 'Salaries & Wages', 'expense', false, '62', 60),
('6202', 'real_estate', 'إيجار مكاتب', 'Office Rent', 'expense', false, '62', 61),
('6203', 'real_estate', 'مصاريف تسويق وإعلان', 'Marketing & Advertising', 'expense', false, '62', 62),
('6204', 'real_estate', 'مصاريف قانونية واستشارية', 'Legal & Consulting', 'expense', false, '62', 63),
('6205', 'real_estate', 'مصاريف اتصالات وإنترنت', 'Communication & Internet', 'expense', false, '62', 64),
('6206', 'real_estate', 'مصاريف سفر وتنقلات', 'Travel & Transportation', 'expense', false, '62', 65),
('6207', 'real_estate', 'استهلاك أصول ثابتة', 'Depreciation', 'expense', false, '62', 66),
('6208', 'real_estate', 'مصاريف متنوعة', 'Miscellaneous Expenses', 'expense', false, '62', 67),
('6209', 'real_estate', 'عمولات بنكية', 'Bank Charges', 'expense', false, '62', 68),
('6210', 'real_estate', 'فوائد تمويل', 'Finance Charges', 'expense', false, '62', 69),
('6211', 'real_estate', 'ضريبة الزكاة', 'Zakat Tax', 'expense', false, '62', 70);
